/**
 * Articles (blog) — docs/26 §WP-3 moved from markdown-in-repo into an admin
 * module: superadmins write, schedule and publish the player app's `/blog`
 * posts. The body is sanitized rich-text HTML (KA required, EN optional);
 * every EN field falls back to its KA twin on the player app.
 *
 * The lifecycle is a small state machine the API enforces (an invalid
 * transition is a 400); {@link ARTICLE_TRANSITIONS} mirrors it so the UI only
 * ever offers the moves that will succeed.
 */

import { isEnglish, liveLabels } from '../i18n/lang';

export type ArticleStatus = 'draft' | 'ready' | 'scheduled' | 'published' | 'archived';
export type ArticleCategory = 'tips' | 'places' | 'news';

/** The one cover image (media pipeline, docs/22) — web + thumb renditions. */
export interface ArticleCover {
  url: string;
  thumbUrl?: string;
  key?: string;
  thumbKey?: string;
  type: string;
}

/** One FAQ entry — rendered as the post's `FAQPage` JSON-LD block. */
export interface ArticleFaqItem {
  q: string;
  a: string;
  qEn?: string;
  aEn?: string;
}

/** An article as returned by `GET /articles` and `GET /articles/:id`. */
export interface Article {
  _id: string;
  title: string;
  titleEn?: string;
  /** Latin URL slug (`/blog/:slug`); generated by the API when omitted. */
  slug: string;
  excerpt?: string;
  excerptEn?: string;
  bodyHtml: string;
  bodyHtmlEn?: string;
  cover?: ArticleCover | null;
  category: ArticleCategory;
  tags: string[];
  faq: ArticleFaqItem[];
  status: ArticleStatus;
  /** ISO instant a `scheduled` article goes live. */
  publishAt?: string | null;
  /** ISO instant the article (last) went live. */
  publishedAt?: string | null;
  seoTitle?: string;
  seoTitleEn?: string;
  seoDescription?: string;
  seoDescriptionEn?: string;
  /** Facility ids the post links to (CTA cards, internal links). */
  relatedFacilities: string[];
  /** Read-only, computed by the API from the KA body. */
  wordCount: number;
  /** Read-only, computed by the API from the KA body. */
  readingMinutes: number;
  /** Read-only byline («Sport Space რედაქცია»). */
  author: string;
  createdAt?: string;
  updatedAt?: string;
}

/**
 * `POST /articles` body. Optional keys are omitted when empty; the status is
 * not part of it — a new article is always a draft and moves through
 * `PATCH /articles/:id/status`.
 */
export interface CreateArticleDto {
  title: string;
  titleEn?: string;
  slug?: string;
  excerpt?: string;
  excerptEn?: string;
  bodyHtml: string;
  bodyHtmlEn?: string;
  cover?: ArticleCover;
  category: ArticleCategory;
  tags: string[];
  faq: ArticleFaqItem[];
  seoTitle?: string;
  seoTitleEn?: string;
  seoDescription?: string;
  seoDescriptionEn?: string;
  relatedFacilities: string[];
}

/**
 * `PUT /articles/:id` body — every key optional. An explicit `null` clears an
 * optional field server-side (`cover: null` removes the cover image);
 * omitting a key leaves it untouched.
 */
export type UpdateArticleDto = {
  [K in keyof CreateArticleDto]?: CreateArticleDto[K] | null;
};

/** `PATCH /articles/:id/status` body; `publishAt` only with `scheduled`. */
export interface ArticleStatusChange {
  status: ArticleStatus;
  publishAt?: string;
}

/** Query of `GET /articles`; undefined keys are left out of the URL. */
export interface ArticleListQuery {
  page: number;
  limit: number;
  q?: string;
  status?: ArticleStatus;
  category?: ArticleCategory;
}

// ── status machine ──────────────────────────────────────────────────────────

/**
 * Allowed moves, mirrored from the API: draft → ready; draft|ready →
 * published (now) or scheduled (with publishAt); scheduled → ready | draft |
 * published; published → archived; archived → ready | draft.
 */
export const ARTICLE_TRANSITIONS: Readonly<Record<ArticleStatus, readonly ArticleStatus[]>> = {
  draft: ['ready', 'published', 'scheduled'],
  ready: ['published', 'scheduled'],
  scheduled: ['ready', 'draft', 'published'],
  published: ['archived'],
  archived: ['ready', 'draft'],
};

export function canTransition(from: ArticleStatus, to: ArticleStatus): boolean {
  return ARTICLE_TRANSITIONS[from]?.includes(to) ?? false;
}

// ── labels + badge classes ──────────────────────────────────────────────────
// Values stay RAW Georgian — `liveLabels` translates on every read.

export const ARTICLE_STATUS_LABELS: Record<ArticleStatus, string> = liveLabels({
  draft: 'დრაფტი',
  ready: 'მზადაა',
  scheduled: 'დაგეგმილი',
  published: 'გამოქვეყნებული',
  archived: 'არქივში',
});

export const ARTICLE_STATUS_CLASSES: Record<ArticleStatus, string> = {
  draft: 'ss-badge ss-badge--neutral',
  ready: 'ss-badge ss-badge--info',
  scheduled: 'ss-badge ss-badge--warning',
  published: 'ss-badge ss-badge--positive',
  archived: 'ss-badge ss-badge--muted',
};

/**
 * Sense override: the dictionary maps «ადგილები» to "Spots" (tournament
 * capacity), but the blog category means places — so the category names
 * carry their own English and read the language signal at render time.
 */
const ARTICLE_CATEGORY_NAMES: Record<ArticleCategory, { ka: string; en: string }> = {
  tips: { ka: 'რჩევები', en: 'Tips' },
  places: { ka: 'ადგილები', en: 'Places' },
  news: { ka: 'სიახლეები', en: 'News' },
};

/** «რჩევები» / "Tips" … — live: call it at render time, never store the result. */
export function articleCategoryLabel(category: ArticleCategory): string {
  const name = ARTICLE_CATEGORY_NAMES[category];
  if (!name) return category;
  return isEnglish() ? name.en : name.ka;
}

export const ARTICLE_STATUSES = Object.keys(ARTICLE_STATUS_LABELS) as ArticleStatus[];
export const ARTICLE_CATEGORIES = Object.keys(ARTICLE_CATEGORY_NAMES) as ArticleCategory[];

// ── caps (mirrored from the API contract, so the form stops before a 400) ───

export const ARTICLE_TITLE_MAX = 160;
export const ARTICLE_EXCERPT_MAX = 300;
export const ARTICLE_SEO_TITLE_MAX = 70;
export const ARTICLE_SEO_DESCRIPTION_MAX = 170;
export const ARTICLE_TAGS_MAX = 10;
export const ARTICLE_FAQ_MAX = 10;
export const ARTICLE_RELATED_FACILITIES_MAX = 6;
/** UI guards (not in the contract): a tag is a short label, a slug a short URL. */
export const ARTICLE_TAG_MAX_LENGTH = 50;
export const ARTICLE_SLUG_MAX = 100;

/** `slug` wire format: lowercase latin words joined by single hyphens. */
export const ARTICLE_SLUG_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/** docs/26 article spec: 900–1,600 words — below 900 a post reads as thin. */
export const ARTICLE_SEO_MIN_WORDS = 900;
/** Reading speed behind the live «N წთ» estimate (the API's value wins on save). */
export const ARTICLE_WORDS_PER_MINUTE = 200;

/** Minutes to read `words` words; 0 for an empty body. */
export function readingMinutesFor(words: number): number {
  return words > 0 ? Math.max(1, Math.ceil(words / ARTICLE_WORDS_PER_MINUTE)) : 0;
}
