/**
 * Coaches directory (docs/26 §WP-1d): public profile pages
 * (`/padelis-trenerebi/:slug` on the player site) for padel coaches. An
 * academy's operators (ADMIN) manage their own academy's coaches; superadmins
 * manage every coach, including independent ones (`academy: null`). Money
 * crosses the wire as integer **tetri** (1 GEL = 100 tetri); the admin form
 * edits GEL and converts at the edge (money.util).
 */

import { liveLabels } from '../i18n/lang';

export type CoachStatus = 'draft' | 'published';
export type CoachLanguage = 'ka' | 'en' | 'ru' | 'es' | 'tr' | 'de' | 'fr';
export type CoachLevel = 'kids' | 'beginner' | 'intermediate' | 'advanced';

/** The one profile photo (media pipeline, docs/22) — web + thumb renditions. */
export interface CoachPhoto {
  url: string;
  thumbUrl?: string;
  key?: string;
  thumbKey?: string;
  type: string;
}

/** A coach as returned by `GET /coaches` and `GET /coaches/:id`. */
export interface Coach {
  _id: string;
  name: string;
  nameEn?: string;
  /** Latin URL slug; generated by the API when omitted on create. */
  slug: string;
  photo?: CoachPhoto | null;
  bio: string;
  bioEn?: string;
  languages: CoachLanguage[];
  levels: CoachLevel[];
  certifications: string[];
  /** One-to-one lesson price, integer tetri. */
  priceIndividualTetri?: number;
  /** Group lesson price per player, integer tetri. */
  priceGroupTetri?: number;
  phone?: string;
  instagram?: string;
  whatsapp?: string;
  /** Stored town name ('Tbilisi', 'Batumi', … or any other town). */
  city: string;
  /** Tbilisi district id (DISTRICT_OPTIONS). */
  district?: string;
  /** Owning academy id; null / absent = an independent coach. */
  academy?: string | null;
  /** Partner facility ids the coach teaches at (≤ 6). */
  facilities: string[];
  /** Directory venue ids the coach teaches at (≤ 6). */
  venues: string[];
  status: CoachStatus;
  createdAt?: string;
  updatedAt?: string;
}

/** `POST /coaches` body. Optional keys are omitted when empty. */
export interface CreateCoachDto {
  name: string;
  nameEn?: string;
  /** Omit to let the API generate it from the name. */
  slug?: string;
  photo?: CoachPhoto;
  bio: string;
  bioEn?: string;
  languages?: CoachLanguage[];
  levels?: CoachLevel[];
  certifications?: string[];
  priceIndividualTetri?: number;
  priceGroupTetri?: number;
  phone?: string;
  instagram?: string;
  whatsapp?: string;
  city: string;
  district?: string;
  /** SUPERADMIN only: omit for an independent coach. An ADMIN never sends it. */
  academy?: string;
  facilities?: string[];
  /** SUPERADMIN only (the venues directory is a superadmin read). */
  venues?: string[];
  status?: CoachStatus;
}

/**
 * `PUT /coaches/:id` body — every key optional; an omitted key is left
 * untouched. An explicit `null` clears an optional fact (English texts, photo,
 * prices, contacts, district) — `photo: null` removes the photo, and
 * `academy: null` makes the coach independent (superadmin only). Required
 * content (name, bio, city, slug, status) and the lists never go over as null;
 * an empty list is `[]`.
 */
export type UpdateCoachDto = {
  [K in keyof CreateCoachDto]?: CreateCoachDto[K] | null;
};

/** Query of `GET /coaches`; undefined keys are left out of the URL. */
export interface CoachListQuery {
  page: number;
  limit: number;
  q?: string;
  status?: CoachStatus;
  city?: string;
  academy?: string;
}

// ── labels + badge classes ──────────────────────────────────────────────────
// Values stay RAW Georgian — `liveLabels` translates on every read, so a
// language flip re-renders instead of going stale (i18n rule: never bake).

export const COACH_STATUS_LABELS: Record<CoachStatus, string> = liveLabels({
  draft: 'დრაფტი',
  published: 'გამოქვეყნებული',
});

export const COACH_STATUS_CLASSES: Record<CoachStatus, string> = {
  draft: 'ss-badge ss-badge--neutral',
  published: 'ss-badge ss-badge--positive',
};

/** Teaching languages, in the order the chips render. */
export const COACH_LANGUAGE_LABELS: Record<CoachLanguage, string> = liveLabels({
  ka: 'ქართული',
  en: 'ინგლისური',
  ru: 'რუსული',
  es: 'ესპანური',
  tr: 'თურქული',
  de: 'გერმანული',
  fr: 'ფრანგული',
});

/** Who a coach teaches, youngest / newest first. */
export const COACH_LEVEL_LABELS: Record<CoachLevel, string> = liveLabels({
  kids: 'ბავშვები',
  beginner: 'დამწყები',
  intermediate: 'საშუალო',
  advanced: 'გამოცდილი',
});

export const COACH_STATUSES = Object.keys(COACH_STATUS_LABELS) as CoachStatus[];
export const COACH_LANGUAGES = Object.keys(COACH_LANGUAGE_LABELS) as CoachLanguage[];
export const COACH_LEVELS = Object.keys(COACH_LEVEL_LABELS) as CoachLevel[];

/** A new coach teaches in Georgian unless told otherwise (the API default). */
export const COACH_DEFAULT_LANGUAGES: readonly CoachLanguage[] = ['ka'];

/** `slug` wire format: lowercase latin words joined by single hyphens. */
export const COACH_SLUG_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

// Length / range caps mirrored from the API DTO (coach.constants.ts), so the
// form stops the operator before the API would 400.
export const COACH_NAME_MAX = 120;
export const COACH_SLUG_MAX = 80;
export const COACH_BIO_MAX = 4000;
export const COACH_CERTIFICATIONS_MAX = 10;
export const COACH_CERTIFICATION_MAX = 120;
export const COACH_CITY_MAX = 80;
export const COACH_PHONE_MAX = 40;
export const COACH_URL_MAX = 500;
/** Facilities / directory venues a coach teaches at (each list). */
export const COACH_PLACES_MAX = 6;
/** 10 000 GEL (the API caps lesson prices at 1 000 000 tetri). */
export const COACH_MAX_PRICE_GEL = 10_000;

/** SEO guidance: a coach page reads as thin below this many bio words. */
export const COACH_SEO_MIN_WORDS = 150;
