/**
 * Venues directory (docs/26 §WP-1b): EVERY padel venue in Georgia — partner or
 * not — managed by superadmins and rendered as SEO directory pages. A venue is
 * separate from a bookable `Facility`; `partnerFacility` links the two once a
 * club signs up. Money crosses the wire as integer **tetri** (1 GEL = 100
 * tetri); the admin form edits GEL and converts at the edge (money.util).
 */

import { liveLabels, tr } from '../i18n/lang';

export type VenueKind = 'club' | 'resort';
export type VenueStatus = 'draft' | 'published' | 'opening_soon' | 'closed';
export type VenueSource = 'manual' | 'import';

export type VenueDay = 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';

/** Week order of the opening-hours editor (Monday first, as the API keys it). */
export const VENUE_DAYS: readonly VenueDay[] = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];

/** One open day: 'HH:mm' bounds. `close` may be earlier than `open` (past midnight). */
export interface VenueDayHours {
  open: string;
  close: string;
}

/** Per-day hours; `null` = closed that day. An absent object = hours unknown. */
export type VenueOpeningHours = Record<VenueDay, VenueDayHours | null>;

/**
 * A venue image — the `cover` (page hero + card) or the club `logo`, uploaded
 * under media scope `venue-photo` — as the admin read returns it (the API's
 * IMedia, whose `size` may be absent). `metadata.sourceUrl` records where a
 * borrowed photo came from, so a takedown request can be traced; the admin
 * never sends `metadata` back.
 */
export interface VenueImage {
  url: string;
  type: string;
  thumbUrl?: string;
  key?: string;
  thumbKey?: string;
  size?: number;
  metadata?: { sourceUrl?: string; [key: string]: unknown } | null;
  id?: string;
}

/** A venue as returned by `GET /venues` and `GET /venues/:id`. */
export interface Venue {
  _id: string;
  name: string;
  nameEn?: string;
  /** Latin URL slug; generated by the API when omitted on create. */
  slug: string;
  /** Stored town name ('Tbilisi', 'Batumi', … or any other town). */
  city: string;
  /** Read-only, derived by the API from `city`. */
  citySlug?: string;
  /** Tbilisi district id (DISTRICT_OPTIONS). */
  district?: string;
  /** Landmark id (LANDMARK_OPTIONS). */
  landmark?: string;
  address?: string;
  lat?: number;
  lng?: number;
  phone?: string;
  website?: string;
  mapsUrl?: string;
  instagram?: string;
  facebook?: string;
  tiktok?: string;
  whatsapp?: string;
  courtsCount: number;
  indoorCourtsCount: number;
  hasRoof: boolean;
  priceMinTetri?: number;
  priceMaxTetri?: number;
  racketRentalTetri?: number;
  openingHours?: VenueOpeningHours | null;
  description?: string;
  descriptionEn?: string;
  cover?: VenueImage | null;
  logo?: VenueImage | null;
  kind: VenueKind;
  status: VenueStatus;
  /** Linked bookable facility id once the venue became a partner. */
  partnerFacility?: string | null;
  /** Read-only: how the record entered the directory. */
  source: VenueSource;
  /** Read-only: where an imported record was scraped from. */
  sourceUrl?: string;
  createdAt?: string;
  updatedAt?: string;
}

/** `POST /venues` body. Optional keys are omitted when empty. */
export interface CreateVenueDto {
  name: string;
  nameEn?: string;
  /** Omit to let the API generate it from the name. */
  slug?: string;
  city: string;
  district?: string;
  landmark?: string;
  address?: string;
  lat?: number;
  lng?: number;
  phone?: string;
  website?: string;
  mapsUrl?: string;
  instagram?: string;
  facebook?: string;
  tiktok?: string;
  whatsapp?: string;
  courtsCount: number;
  indoorCourtsCount: number;
  hasRoof: boolean;
  priceMinTetri?: number;
  priceMaxTetri?: number;
  racketRentalTetri?: number;
  openingHours?: VenueOpeningHours;
  description?: string;
  descriptionEn?: string;
  /** Media fields only (url, type, thumbUrl, key, thumbKey). */
  cover?: VenueImage;
  logo?: VenueImage;
  kind: VenueKind;
  status: VenueStatus;
  partnerFacility?: string;
}

/**
 * `PUT /venues/:id` body — every key optional. An explicit `null` clears an
 * optional field server-side (a cleared partner link, website, price bound, a
 * whole opening-hours block, the cover or logo …); omitting a key leaves it
 * untouched.
 */
export type UpdateVenueDto = {
  [K in keyof CreateVenueDto]?: CreateVenueDto[K] | null;
};

/** Query of `GET /venues`; undefined keys are left out of the URL. */
export interface VenueListQuery {
  page: number;
  limit: number;
  q?: string;
  city?: string;
  district?: string;
  landmark?: string;
  kind?: VenueKind;
  status?: VenueStatus;
}

// ── labels + badge classes ──────────────────────────────────────────────────
// Values stay RAW Georgian — `liveLabels` translates on every read, so a
// language flip re-renders instead of going stale (i18n rule: never bake).

export const VENUE_STATUS_LABELS: Record<VenueStatus, string> = liveLabels({
  draft: 'დრაფტი',
  published: 'გამოქვეყნებული',
  opening_soon: 'მალე გაიხსნება',
  closed: 'დახურულია',
});

export const VENUE_STATUS_CLASSES: Record<VenueStatus, string> = {
  draft: 'ss-badge ss-badge--neutral',
  published: 'ss-badge ss-badge--positive',
  opening_soon: 'ss-badge ss-badge--warning',
  closed: 'ss-badge ss-badge--negative',
};

export const VENUE_KIND_LABELS: Record<VenueKind, string> = liveLabels({
  club: 'კლუბი',
  resort: 'კურორტი',
});

export const VENUE_KIND_CLASSES: Record<VenueKind, string> = {
  club: 'ss-badge ss-badge--accent',
  resort: 'ss-badge ss-badge--info',
};

export const VENUE_SOURCE_LABELS: Record<VenueSource, string> = liveLabels({
  manual: 'ხელით',
  import: 'იმპორტი',
});

export const VENUE_SOURCE_CLASSES: Record<VenueSource, string> = {
  manual: 'ss-badge ss-badge--neutral',
  import: 'ss-badge ss-badge--info',
};

export const VENUE_DAY_LABELS: Record<VenueDay, string> = liveLabels({
  mon: 'ორშაბათი',
  tue: 'სამშაბათი',
  wed: 'ოთხშაბათი',
  thu: 'ხუთშაბათი',
  fri: 'პარასკევი',
  sat: 'შაბათი',
  sun: 'კვირა',
});

export const VENUE_STATUSES = Object.keys(VENUE_STATUS_LABELS) as VenueStatus[];
export const VENUE_KINDS = Object.keys(VENUE_KIND_LABELS) as VenueKind[];

// RAW Georgian — see VENUE_CITY_OPTIONS.
const VENUE_CITY_OPTIONS_KA: readonly { id: string; name: string }[] = [
  { id: 'Tbilisi', name: 'თბილისი' },
  { id: 'Tskneti', name: 'წყნეთი' },
  { id: 'Rustavi', name: 'რუსთავი' },
  { id: 'Batumi', name: 'ბათუმი' },
  { id: 'Kutaisi', name: 'ქუთაისი' },
];

/**
 * The directory's named towns (the facility form's CITY_OPTIONS covers only
 * the bookable ones). The latin `id` is the stored `city`; any other town is
 * stored as typed. `name` is a live getter — it follows the language toggle.
 */
export const VENUE_CITY_OPTIONS: readonly { id: string; name: string }[] =
  VENUE_CITY_OPTIONS_KA.map(({ id, name }) => ({
    id,
    get name(): string {
      return tr(name);
    },
  }));

/** Display label of a stored city: a named town translates, any other shows as typed. */
export function venueCityName(city: string | undefined | null): string {
  if (!city) return '';
  return VENUE_CITY_OPTIONS.find((c) => c.id === city)?.name ?? city;
}

/** `slug` wire format: lowercase latin words joined by single hyphens. */
export const VENUE_SLUG_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/** 'HH:mm', 00:00–23:59. */
export const VENUE_TIME_RE = /^([01]\d|2[0-3]):[0-5]\d$/;

// Length / range caps mirrored from the API DTO (venue.constants.ts), so the
// form stops the operator before the API would 400.
export const VENUE_NAME_MAX = 120;
export const VENUE_SLUG_MAX = 80;
export const VENUE_TEXT_MAX = 200;
export const VENUE_URL_MAX = 500;
export const VENUE_DESCRIPTION_MAX = 4000;
export const VENUE_MAX_COURTS = 100;
/** 10 000 GEL (the API caps prices at 1 000 000 tetri). */
export const VENUE_MAX_PRICE_GEL = 10_000;

/** SEO guidance: a directory page reads as thin below this many words. */
export const VENUE_SEO_MIN_WORDS = 100;
